# Generated by Django 4.1.4 on 2023-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chairman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=True, max_length=150)),
                ('password', models.CharField(default=True, max_length=150)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('dept_name', models.CharField(default=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='examcontroller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.TextField(default=True)),
                ('name', models.CharField(default=True, max_length=150)),
                ('password', models.CharField(default=True, max_length=150)),
                ('email', models.EmailField(default=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='hallprovost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=True, max_length=150)),
                ('password', models.CharField(default=True, max_length=150)),
                ('email', models.EmailField(default=True, max_length=254)),
                ('hall_name', models.TextField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regi_no', models.TextField(default=True)),
                ('address', models.TextField(default=True)),
                ('profile_pic', models.FileField(default=True, upload_to='')),
                ('session_start_year', models.DateField(blank=True, null=True)),
                ('dept_name', models.TextField(default=True)),
                ('hall_name', models.TextField(default=True)),
                ('name', models.CharField(default=True, max_length=150)),
                ('password', models.CharField(default=True, max_length=150)),
                ('email', models.EmailField(default=True, max_length=254)),
            ],
        ),
    ]
