# Generated by Django 4.1.4 on 2023-03-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adduser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_start_year',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
