# Generated by Django 4.1.4 on 2023-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_chairman_dept_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chairman',
            name='name',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='examcontroller',
            name='name',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='hallprovost',
            name='name',
            field=models.TextField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.TextField(default=1),
        ),
    ]
