# Generated by Django 4.1.4 on 2023-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_chairman_name_examcontroller_name_hallprovost_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hallprovost',
            old_name='name',
            new_name='hall_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='chairman',
            name='name',
        ),
        migrations.RemoveField(
            model_name='examcontroller',
            name='name',
        ),
        migrations.AddField(
            model_name='chairman',
            name='dept_name',
            field=models.CharField(default=True, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='dept_name',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session_start_year',
            field=models.DateField(default=True),
        ),
    ]
