# Generated by Django 4.1.4 on 2023-02-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_name_hallprovost_hall_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
