# Generated by Django 4.1.4 on 2023-02-08 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_student_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_start_year',
        ),
    ]
