# Generated by Django 4.1.4 on 2023-02-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_student_session_start_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='session_start_year',
            field=models.DateField(default=True),
        ),
    ]
