# Generated by Django 4.1.4 on 2023-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_student_session_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='session_start_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
