# Generated by Django 4.1.4 on 2023-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField(default=1)),
                ('regi_no', models.CharField(default='0', max_length=250)),
                ('course_name', models.CharField(default='true', max_length=250)),
                ('course_code', models.CharField(default='true', max_length=250)),
                ('course_credit', models.CharField(default='true', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='permission_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.TextField(default='cse', max_length=250)),
                ('hall_name', models.TextField(default='hall', max_length=250)),
                ('semester_no', models.IntegerField(default=1)),
                ('regi_no', models.CharField(default='0', max_length=250)),
                ('chairman_permission', models.BooleanField(default=False)),
                ('examcontroller_permission', models.BooleanField(default=False)),
                ('hallprovost_permission', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.TextField(default='cse', max_length=250)),
                ('hall_name', models.TextField(default='hall', max_length=250)),
                ('regi_no', models.CharField(default='0', max_length=250)),
                ('phn_nmbr', models.CharField(default='01', max_length=30)),
                ('semester_no', models.IntegerField(default=1)),
                ('bank_receipt', models.CharField(default='11', max_length=30)),
                ('bank_receipt_image', models.FileField(upload_to='')),
            ],
        ),
    ]
