# Generated by Django 4.1.4 on 2023-01-31 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dept_name', models.CharField(max_length=100)),
                ('regi_no', models.PositiveIntegerField()),
                ('session', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('village', models.CharField(max_length=100)),
                ('zilla', models.CharField(max_length=100)),
                ('post_office', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phn_nmbr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='registration2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profileimage')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
