# Generated by Django 4.1.4 on 2023-02-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=250)),
                ('course_code', models.CharField(max_length=250)),
                ('course_credit', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='images/')),
                ('name_1', models.CharField(max_length=100)),
                ('uploaded_at_1', models.DateTimeField(auto_now_add=True)),
                ('image_2', models.ImageField(upload_to='images/')),
                ('name_2', models.CharField(max_length=100)),
                ('uploaded_at_2', models.DateTimeField(auto_now_add=True)),
                ('image_3', models.ImageField(upload_to='images/')),
                ('name_3', models.CharField(max_length=100)),
                ('uploaded_at_3', models.DateTimeField(auto_now_add=True)),
                ('image_4', models.ImageField(upload_to='images/')),
                ('name_4', models.CharField(max_length=100)),
                ('uploaded_at_4', models.DateTimeField(auto_now_add=True)),
                ('image_5', models.ImageField(upload_to='images/')),
                ('name_5', models.CharField(max_length=100)),
                ('uploaded_at_5', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='slog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='registration2',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='phn_nmbr',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='village',
        ),
        migrations.AlterField(
            model_name='registration1',
            name='dept_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='post_office',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='regi_no',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='session',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='zilla',
            field=models.CharField(max_length=250),
        ),
    ]
