# Generated by Django 4.1.4 on 2023-02-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission_model',
            name='pdf_file',
        ),
    ]
