# Generated by Django 4.1.4 on 2023-02-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_coursecode_image_slog_delete_registration2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='uploaded_at_1',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_1',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name_5',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='uploaded_at_5',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_1',
            field=models.ImageField(upload_to='my_image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_2',
            field=models.ImageField(upload_to='my_image'),
        ),
    ]
