# Generated by Django 4.1.4 on 2023-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_permission_model_chairman_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission_model',
            name='chairman_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission_model',
            name='examcontroller_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='permission_model',
            name='hallprovost_permission',
            field=models.BooleanField(default=False),
        ),
    ]
