# Generated by Django 4.1.4 on 2023-02-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_pdffile_remove_registration1_id_registration1_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecode',
            name='id',
        ),
        migrations.AddField(
            model_name='coursecode',
            name='course_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
