# Generated by Django 4.1.4 on 2023-02-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_permission_model_chairman_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission_model',
            name='dept_name',
            field=models.CharField(default='cse', max_length=250),
        ),
        migrations.AddField(
            model_name='permission_model',
            name='hall_name',
            field=models.CharField(default='hall', max_length=250),
        ),
    ]
