# Generated by Django 4.1.4 on 2023-02-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_coursecode_id_coursecode_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='PdfFile',
        ),
        migrations.DeleteModel(
            name='slog',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='post_office',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='session',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='village',
        ),
        migrations.RemoveField(
            model_name='registration1',
            name='zilla',
        ),
        migrations.AddField(
            model_name='registration1',
            name='bank_receipt',
            field=models.IntegerField(default=True, unique=True),
        ),
        migrations.AddField(
            model_name='registration1',
            name='bank_receipt_image',
            field=models.FileField(default=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='registration1',
            name='courses',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='registration1',
            name='semester_no',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='registration1',
            name='phn_nmbr',
            field=models.CharField(default=True, max_length=250, unique=True),
        ),
    ]
